doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname:               insiders
                host:                 localhost
                port:                 ~
                user:                 root
                password:             root
                charset:              "UTF8"
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity\'
                alias: App
