website:
    resource: ../src/Controller/
    type: annotation

admin:
    resource: '@EasyAdminBundle/Controller/AdminController.php'
    prefix: /admin
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
